name: Question
description: Ask a question
labels:
  - type:question
body:
  - type: textarea
    id: summary
    attributes:
      label: Question
      description: Describe what you are trying to achieve and/or the difficulties you are facing.
    validations:
      required: true
